require_relative 'lib/piece'
require_relative 'lib/king'
require_relative 'lib/queen'
require_relative 'lib/rook'
require_relative 'lib/bishop'
require_relative 'lib/pawn'
require_relative 'lib/knight'